package rs.ac.bg.etf.pp1;

import java_cup.runtime.*;
import org.apache.log4j.*;
import rs.ac.bg.etf.pp1.ast.*;


parser code {:
	
	boolean loggingEnabled = false;
	boolean errorDetected = false;
	Logger log = Logger.getLogger(getClass());

   
   	// Redefined error-reporting methods
     
    public void report_fatal_error(String message, Object info) throws java.lang.Exception {
      done_parsing();
      report_error(message, info);
    }
  
    public void syntax_error(Symbol cur_token) {
        report_error("\nSintaksna greska", cur_token);
    }
  
    public void unrecovered_syntax_error(Symbol cur_token) throws java.lang.Exception {
        report_fatal_error("Fatalna greska, parsiranje se ne moze nastaviti", cur_token);
    }

    public void report_error(String message, Object info) {
    	errorDetected = true;
    	report_info(message, info);
    }
    
    public void report_info(String message, Object info) {
    	StringBuilder msg = new StringBuilder(message); 
    	if (info instanceof Symbol) {
    		msg.append (" na liniji ").append(((Symbol)info).left);
    		msg.append (" na simbolu ").append(((Symbol)info).sym);
    	}
        log.info(msg.toString());
    }
    
:}

scan with {:
	Symbol s = this.getScanner().next_token();
	if (loggingEnabled && s != null && s.value != null) 
		log.info(s.toString() + " " + s.value.toString());
	return s;
:}

terminal  
	PROGRAM, DOT, LBRACK, RBRACK, INTERFACE, RPAREN, IF, CLASS, BREAK, ELSE, 
	GT, NEW, RBRACE, LT, GE, CONTINUE, MAP, DEC, MUL, LE, CONST,
	PRINT, LPAREN, READ, NE, ADD, SUB, INC, LBRACE, DIV, OR, AND, RETURN,
	EQ, EQUAL, VOID, MOD, UNION, DO, COMMA, WHILE, SEMI, EXTENDS, COL;
	
terminal String IDENT;
terminal Integer NUMBER;
terminal Character CHAR;
terminal Boolean BOOL;

nonterminal 
	Setop, Relop, Mulop, Addop, Assignop, Label, DoToken, CondTerm,
	DesignatorStatement, Statement, FormPars, Condition,
	MethodDecl, StatementList, VarDeclList, MethodSignature, InterfaceDecl,
	InterfaceBody, ClassBody, MethodDeclList, VarDecl, ProgramDeclarations,
	VarDeclNoType, VarName, ConstDecl, ConstDeclNoType, ConstAssign, 
	ProgramName, Program, ProgramDeclList, MethodReturnType,
	FormParVar, ClassName, ExtendedClassName, ClassFields, InterfaceName;
	
nonterminal rs.etf.pp1.symboltable.concepts.Obj
	Designator, MethodName, ClassDecl;
	
nonterminal rs.etf.pp1.symboltable.concepts.Struct
	Expr, ExprList, Factor, Term, CallPars, ActPars, CondFact,
	Type;
	
precedence left ELSE;

Program ::= (Program) PROGRAM ProgramName ProgramDeclarations LBRACE MethodDeclList RBRACE
			;
			
ProgramName ::=	(ProgramName) IDENT
				;
				
ProgramDeclarations ::= (ProgramDeclarations) ProgramDeclList
						;

ProgramDeclList ::=	(ProgramDeclList_ConstDecl) ProgramDeclList ConstDecl
					|
					(ProgramDeclList_VarDecl) ProgramDeclList VarDecl
					|
					(ProgramDeclList_ClassDecl) ProgramDeclList ClassDecl
					|
					(ProgramDeclList_InterfaceDecl) ProgramDeclList InterfaceDecl
					|
					(ProgramDeclList_Epsilon) /* epsilon */
					;

ConstAssign ::=	(ConstAssign_Num) IDENT EQUAL NUMBER
				|
				(ConstAssign_Char) IDENT EQUAL CHAR
				|
				(ConstAssign_Bool) IDENT EQUAL BOOL
				;

ConstDeclNoType ::=	(ConstDeclNoType_ConstAssing) ConstDeclNoType COMMA ConstAssign
					|
					(ConstDeclNoType_Epsilon) /* epsilon */
					;

ConstDecl ::= 	(ConstDecl) CONST Type ConstAssign ConstDeclNoType SEMI
				;

VarName ::=	(VarName_NonArray) IDENT 
			|
			(VarName_Array) IDENT LBRACK RBRACK
			;

VarDeclNoType ::= 	(VarDeclNoType_VarName) VarDeclNoType COMMA VarName
					|
					(VarDeclNoType_Epsilon) /* epsilon */
					;

VarDecl ::=	(VarDecl) Type VarName VarDeclNoType SEMI
			;

MethodDeclList ::=	(MethodDeclList_MethodDecl) MethodDeclList MethodDecl
					|
					(MethodDeclList_Epsilon) /* epsilon */
					;

ClassBody ::=	(ClassBody_Fields) ClassFields
				|
				(ClassBody_FieldsAndMethods) ClassFields LBRACE MethodDeclList RBRACE  
				;
				
ClassFields ::=	(ClassFields) VarDeclList
				;

ClassDecl ::= 	(ClassDecl_Derived) CLASS ClassName EXTENDS ExtendedClassName LBRACE ClassBody RBRACE
				|
				(ClassDecl_NonDerived) CLASS ClassName LBRACE ClassBody RBRACE
				;
				
ExtendedClassName ::= 	(ExtendedClassName) Type
						;
				
ClassName ::=	(ClassName) IDENT
				;

InterfaceBody ::=	(InterfaceBody_MethodDecl) InterfaceBody MethodDecl
					|
					(InterfaceBody_MethodSignature) InterfaceBody MethodSignature SEMI 
					|
					(InterfaceBody_Epsilon) /* epsilon */
					; 

InterfaceDecl ::=	(InterfaceDecl) INTERFACE InterfaceName LBRACE InterfaceBody RBRACE
					;
					
InterfaceName ::=	(InterfaceName) IDENT
					;

MethodSignature ::=	(MethodSignature_NoPars) MethodReturnType MethodName LPAREN RPAREN
					|
					(MethodSignature_Pars) MethodReturnType MethodName LPAREN FormPars RPAREN
					;
					
MethodReturnType ::=	(MethodReturnType_Void) VOID
						|
						(MethodReturnType_Type) Type
						;
					
MethodName ::= 	(MethodName) IDENT
				;
				
VarDeclList ::=	(VarDeclList_VarDecl) VarDeclList VarDecl
				|
				(VarDeclList_Epsilon) /* epsilon */
				;
				
MethodDecl ::=	(MethodDecl) MethodSignature VarDeclList LBRACE StatementList RBRACE
				;

FormPars ::= 	(FormPars_FormParVar) FormParVar
				|
				(FormPars_FormParVarList) FormPars COMMA FormParVar
				;
				
FormParVar ::=	(FormParVar_NonArray) Type IDENT 
				|
				(FormParVar_Array) Type IDENT LBRACK RBRACK
				;

Type ::=	(Type) IDENT
			;
			
StatementList ::= 	(StatementList_Statement) StatementList Statement
					|
					(StatementList_Epsilon) /* epsilon */
					;

Statement ::= 	(Statement_DesignatorStatement) DesignatorStatement SEMI
				|
				(Statement_If) IF LPAREN Condition RPAREN Statement
				|
				(Statement_IfElse) IF LPAREN Condition RPAREN Statement ELSE Statement
				|
				(Statement_Break) BREAK SEMI
				|
				(Statement_Continue) CONTINUE SEMI
				|
				(Statement_ReturnVoid) RETURN SEMI
				|
				(Statement_ReturnExpr) RETURN Expr SEMI
				|
				(Statement_Read) READ LPAREN Designator RPAREN SEMI
				|
				(Statement_PrintExpr) PRINT LPAREN Expr RPAREN SEMI
				|
				(Statement_PrintExprWithNum) PRINT LPAREN Expr COMMA NUMBER RPAREN SEMI
				|
				(Statement_DoWhileTrue) DoToken Statement WHILE LPAREN RPAREN SEMI
				|
				(Statement_DoWhileCondition) DoToken Statement WHILE LPAREN Condition RPAREN SEMI
				|
				(Statement_DoWhileConditionWithDesignatorStatement) DoToken Statement WHILE LPAREN Condition COMMA DesignatorStatement RPAREN SEMI
				|
				(Statement_Block) LBRACE StatementList RBRACE
				;
				
DoToken ::=	(DoToken) DO
			;				

DesignatorStatement ::= (DesignatorStatement_AssignExpr) Designator Assignop Expr
						|
						(DesignatorStatement_Call) Designator CallPars
						|
						(DesignatorStatement_Inc) Designator INC
						|
						(DesignatorStatement_Dec) Designator DEC
						|
						(DesignatorStatement_AssignSetop) Designator Assignop Designator Setop Designator
						;

CallPars ::=	(CallPars_ActPars) LPAREN ActPars RPAREN
				|
				(CallPars_Empty) LPAREN RPAREN
				;
				
ActPars ::=	(ActPars_Expr) Expr
			|
			(ActPars_ExprList) ActPars COMMA Expr
			;
			

Condition ::= 	(Condition_CondTerm) CondTerm
				|
				(Condition_OrCondTerm) Condition OR CondTerm
				;

CondTerm ::= 	(CondTerm_CondFact) CondFact
				|
				(CondTerm_AndCondFact) CondTerm AND CondFact
				;
				
				
CondFact ::=	(CondFact_Expr) Expr 
				|
				(CondFact_RelopExpr) Expr Relop Expr
				;

ExprList ::=	(ExprList_Term) Term
				|
				(ExprList_SubTerm) SUB Term
				|
				(ExprList_AddopTerm) ExprList Addop Term
				;

Expr ::=	(Expr_ExprList) ExprList
			|
			(Expr_Map) Designator MAP Designator
			;
				
Term ::= 	(Term_Factor) Factor
			|
			(Term_MulopFactor) Term Mulop Factor
			;

Factor ::= 	(Factor_Designator) Designator
			|
			(Factor_DesignatorCall) Designator CallPars
			|
			(Factor_NumConst) NUMBER
			|
			(Factor_CharConst) CHAR
			|
			(Factor_BoolConst) BOOL
			|
			(Factor_NewArray) NEW Type LBRACK Expr RBRACK
			|
			(Factor_NewObject) NEW Type CallPars
			|
			(Factor_Expr) LPAREN Expr RPAREN
			;

Designator ::=	(Designator_Ident) IDENT
				|
				(Designator_MemberAccess) Designator DOT IDENT
				|
			 	(Designator_ArrayAccess) Designator LBRACK Expr RBRACK
			 	;

				
Label ::= 	(Label) IDENT
			;
				
Assignop ::=	(Assignop) EQUAL
				;

Relop ::=	(Relop_Equal) EQ
			|
			(Relop_NotEqual) NE
			|
			(Relop_Greater) GT
			|
			(Relop_GreaterOrEqual) GE
			|
			(Relop_Lesser) LT
			|
			(Relop_LesserOrEqual) LE
			;
			
Addop ::=	(Addop_Add) ADD
			|
			(Addop_Sub) SUB
			;
		

Mulop ::= 	(Mulop_Mul) MUL
			|
			(Mulop_Div) DIV
			|
			(Mulop_Mod) MOD
			;

Setop ::= 	(Setop) UNION
			;

